"""
Django settings for saarthi_citizen_backend project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import datetime
from pathlib import Path
from .env  import load_environment
import os

# Load environment variables
ENVIRONMENT=load_environment()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG","FALSE").lower()=='true'

#CSS part
DEBUG_WATERMARK = os.getenv("DEBUG_WATERMARK","FALSE").lower()=='true'

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS","").split(",")


# Application definition

INSTALLED_APPS = [
    "common",
    "citizen",
    "health",
    "users",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'saarthi_citizen_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'saarthi_citizen_backend.wsgi.application'
DB_SCHEMA = os.getenv("DB_SCHEMA","public")

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv("DB_ENGINE"),
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST"),
        'PORT': os.getenv("DB_PORT"),
        'OPTIONS': {
            "options":f'-c search_path={DB_SCHEMA}'
        },
         'POOL_OPTIONS' : {
            'POOL_SIZE': int(os.getenv("DB_POOL","3")),
            'MAX_OVERFLOW': int(os.getenv("DB_MAX_OVERFLOW","2")),
            'RECYCLE': 24 * 60 * 60
        },
        'CONN_MAX_AGE': int(os.getenv("CONN_MAX_AGE","600"))
    },
    'replica': {
        'ENGINE': os.getenv("DB_ENGINE"),
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_REPLICA_HOST"),
        'PORT': os.getenv("DB_PORT"),
        'OPTIONS': {
            "options":f'-c search_path={DB_SCHEMA}'
        },
         'POOL_OPTIONS' : {
            'POOL_SIZE': int(os.getenv("DB_POOL","3")),
            'MAX_OVERFLOW': int(os.getenv("DB_MAX_OVERFLOW","2")),
            'RECYCLE': 24 * 60 * 60
        },
        'CONN_MAX_AGE': int(os.getenv("CONN_MAX_AGE","600"))
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JWT_EXPIRATION_MINUTES = int(os.getenv("JWT_EXPIRATION_MINUTES","60"))
JWT_SECRET_KEY = SECRET_KEY
JWT_ALGORITHM = os.getenv("JWT_ALGORITHM","HS256")
JWT_EXPIRATION_TIME = datetime.timedelta(minutes=JWT_EXPIRATION_MINUTES)
JWT_REFRESH_THRESHOLD  = 0.5  # Refresh token if more than 50% of its lifespan has passed
ENABLE_PRIVILEGE_CHECK = os.getenv("ENABLE_PRIVILEGE_CHECK","True").lower()=='true'
PRIVILEGE_WHITELISTED_PATHS = []

CORS_ALLOW_ALL_ORIGINS = os.getenv("CORS_ALLOW_ALL_ORIGINS","False").lower()=='true'
if not CORS_ALLOW_ALL_ORIGINS:
    CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS","").split(",")
CORS_ALLOW_CREDENTIALS = os.getenv("CORS_ALLOW_CREDENTIALS","True").lower()=='true'    
JWT_AUTH_EXEMPT_PATHS=[]

ENABLE_QUERY_LOGGING = os.getenv("ENABLE_QUERY_LOGGING","True").lower()=='true'

SPECTACULAR_SETTINGS = {
    'TITLE': 'Saarthi Citizen Backend API',
    'DESCRIPTION': 'Saarthi Citizen Backend API',
    'VERSION': '1.0.0'
}
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    
    'formatters': {
        'simple': {
            'format': '%(asctime)s %(levelname)-8s %(message)s',
        },
    },
 'handlers': {
        'console': {   # ✅ THIS WAS MISSING
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    "loggers":{
        "django":{
            "level":os.getenv("LOG_LEVEL","ERROR"),
            "handlers":["console"],
            "propagate":True,
        },
        "django.db.backends":{
            "level":"INFO",
            "handlers":["console"],
            "propagate":False,
        }
    }
}

RATE_LIMIT_SKIP_IPS=[]

# AUTH_USER_MODEL='users.User'