# Generated by Django 5.2.10 on 2026-02-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='pincode',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
