# Generated by Django 5.2.10 on 2026-02-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0002_citizen_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginactivity',
            name='m_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
