# Generated by Django 5.2.10 on 2026-02-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterMaster',
            fields=[
                ('param_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('parameter_key', models.CharField(max_length=100, null=True)),
                ('parameter_value', models.CharField(max_length=600)),
                ('parameter_desc', models.CharField(max_length=255, null=True)),
                ('status', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'parameter_master',
                'managed': False,
            },
        ),
    ]
