# Generated by Django 5.2.10 on 2026-02-06 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'managed': False},
        ),
    ]
