# Generated by Django 5.2.10 on 2026-02-07 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_district_options_alter_services_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'managed': False},
        ),
    ]
