# Generated by Django 5.2.10 on 2026-02-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_district_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assemblyconstituency',
            options={},
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={},
        ),
        migrations.AlterModelOptions(
            name='block',
            options={},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={},
        ),
        migrations.AlterModelOptions(
            name='documentmaster',
            options={},
        ),
        migrations.AlterModelOptions(
            name='domainlookup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='errormessage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='parametermaster',
            options={},
        ),
        migrations.AlterModelOptions(
            name='parliamentaryconstituency',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={},
        ),
        migrations.AlterModelOptions(
            name='trainingcenter',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelOptions(
            name='village',
            options={},
        ),
    ]
