# Generated by Django 5.2.10 on 2026-02-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FcmJson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('json', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fcm_json',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FcmToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(null=True)),
                ('user_type', models.IntegerField(null=True)),
                ('token', models.CharField(max_length=500)),
                ('device_type', models.CharField(max_length=20, null=True)),
                ('created_on', models.DateTimeField(null=True)),
                ('created_by', models.BigIntegerField(null=True)),
                ('updated_on', models.DateTimeField(null=True)),
                ('updated_by', models.BigIntegerField(null=True)),
                ('expiry_time', models.DateTimeField(null=True)),
                ('c_m_no', models.CharField(max_length=15, null=True)),
                ('allow_flag', models.IntegerField(default=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fcm_token',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('token_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(null=True)),
                ('user_type', models.IntegerField(null=True)),
                ('token', models.CharField(max_length=500)),
                ('updated_on', models.DateTimeField(null=True)),
                ('expiry_time', models.DateTimeField(null=True)),
                ('c_m_no', models.CharField(max_length=15, null=True)),
                ('allow_flag', models.IntegerField(default=1, null=True)),
            ],
            options={
                'db_table': 'user_token',
                'managed': True,
            },
        ),
    ]
