# Generated by Django 5.2.10 on 2026-02-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JWTAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='c_m_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
