# Generated by Django 5.2.10 on 2026-02-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_code', models.CharField()),
                ('candidate_type', models.SmallIntegerField(blank=True, null=True)),
                ('kaushal_panjee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sanction_order', models.CharField(blank=True, max_length=50, null=True)),
                ('kb_project_id', models.CharField(blank=True, max_length=50, null=True)),
                ('mpr_project_id', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=500, null=True)),
                ('qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mpr_id', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('category', models.IntegerField(blank=True, null=True)),
                ('pwd', models.IntegerField(blank=True, null=True)),
                ('minority', models.IntegerField(blank=True, null=True)),
                ('religion', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('nature_of_training', models.CharField(blank=True, max_length=50, null=True)),
                ('aadhar', models.CharField(blank=True, max_length=10, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True)),
                ('house_no', models.CharField(blank=True, max_length=50, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=500, null=True)),
                ('interest_freelancer', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('status', models.SmallIntegerField(blank=True, null=True)),
                ('is_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('available_start_time', models.DateTimeField(blank=True, null=True)),
                ('available_end_time', models.DateTimeField(blank=True, null=True)),
                ('available_days', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'candidates',
                'managed': False,
            },
        ),
    ]
